language: python
python:
- "2.5"
#- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"
script: ./setup.py tests
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y libsndfile1 portaudio19-dev
install:
- pip install --allow-external PyAudio --allow-unverified PyAudio PyAudio
- pip install --allow-external ctypes --allow-unverified ctypes ctypes
- pip install -r requirements.txt


