language: python
python:
- "2.5"
- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"
script: ./setup.py tests
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y libsndfile1
install:
- pip install -r requirements.txt


